{% set name = "hmnfusion" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .
  entry_points:
    - {{ name }}=hmnfusion.__main__:main

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - beautifulsoup4
    - et-xmlfile
    - matplotlib-base
    - lxml
    - natsort
    - networkx
    - numpy
    - openpyxl
    - pandas
    - pysam
    - pytest
    - python
    - pyyaml
    - requests
    - snakemake

test:
  imports:
    - {{ name|lower }}
  commands:
    - {{ name|lower }} --help

about:
  home: https://github.com/guillaume-gricourt/HmnFusion
  summary: Analysis fusion from DNA genomics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
