name: hmnfusion
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beautifulsoup4
  - et-xmlfile
  - matplotlib
  - lxml
  - natsort
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pysam
  - pytest
  - pyyaml
  - requests
  - snakemake
  # test
  - anaconda-client
  - conda-build
  # docs
  - sphinx
  - sphinx_rtd_theme
