# syntax=docker/dockerfile:1
FROM  continuumio/miniconda3:4.10.3

RUN apt-get update
RUN apt-get install -y \
    autoconf \
    build-essential \
    libbz2-dev \
    libcurl4-openssl-dev \
    liblzma-dev \
    libncurses5-dev \
    zlib1g-dev

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

RUN conda create \
    -n aligner \
    bwa=0.7.15

RUN conda create \
    -n toolbox \
    gatk=3.8.0 \
    picard=2.9.0 \
    samtools=1.3.1 \
    sickle-trim=1.33

WORKDIR /opt

# HmnFusion
COPY *whl /opt/
RUN pip install --no-cache-dir /opt/*whl

# Download reference
RUN mkdir -p /ref/hg19
RUN --mount=type=secret,id=mysecret \
    hmnfusion download-zenodo \
    --input-zenodo-str 6619597 \
    --input-token-str $(cat /run/secrets/mysecret) \
    --output-directory /ref/hg19

ENTRYPOINT ["hmnfusion"]
