name: hmnfusion
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beautifulsoup4
  - et-xmlfile
  - matplotlib
  - lxml
  - natsort
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pysam
  - pytest
  - python
  - pyyaml
