{% set name = 'hmnfusion' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vvv .
  entry_points:
    - {{ name }}=hmnfusion.__main__:main

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - beautifulsoup4
    - et-xmlfile
    - matplotlib
    - lxml
    - natsort
    - networkx
    - numpy
    - openpyxl
    - pandas
    - pysam
    - pytest
    - python
    - pyyaml
    - requests
    - snakemake

test:
  source_files:
    - tests
  imports:
    - hmnfusion
  requires:
    - pytest
  commands:
    - {{ name }} version
    - python -m pytest

about:
  home: https://github.com/guillaume-gricourt/HmnFusion
  summary: {{ data['description'] }}
  license: Other
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
