{% set name = 'hmnfusion' %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vvv .
  entry_points:
    - {{ name }}=hmnfusion.__main__:main

requirements:
  build:
    - pip
    - pytest
    - python
    - pyyaml
    - setuptools
  run:
    - beautifulsoup4
    - et-xmlfile
    - matplotlib
    - lxml
    - natsort
    - networkx
    - numpy
    - openpyxl
    - pandas
    - pysam
    - pytest
    - python
    - pyyaml

test:
  imports:
    - hmnfusion
  commands:
    - {{ name }} version

about:
  home: https://github.com/guillaume-gricourt/HmnFusion
  license: Other
  license_file: LICENSE.md
