{% set name = 'hmnfusion' %}
{% set data = load_setup_py_data() %}

package:
  name: {{name}}
  version: {{data.version}}

source:
  path: ..

build:
  number: 0
  noarch: python
  entry_points:
    - {{name}}=hmnfusion.__main__:main

requirements:
  build:
    - pip
    - python>=3
    - setuptools
    - beautifulsoup4>=4.9.0
    - natsort>=7.0.0
    - numpy>=1.18.3
    - pandas>=1.0.3
    - pysam>=0.15.4
    - et-xmlfile
    - openpyxl
  run:
    - python>=3
    - beautifulsoup4>=4.9.0
    - natsort>=7.0.0
    - numpy>=1.18.3
    - pandas>=1.0.3
    - pysam>=0.15.4
    - et-xmlfile
    - openpyxl

test:
  imports:
    - hmnfusion
  commands:
    - {{name}} version

about:
  home: https://github.com/guillaume-gricourt/HmnFusion
  license: GPLv3+
  license_file: LICENSE
